/* tslint:disable */
// This file is generated
// Do not edit this file
import * as configuration from "./configuration";
export * as configuration from "./configuration";

export type States = {
  configuration: configuration.Configuration;
}
