/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The shop name from the browser/URL.
 */
export type ShopStoreName = string;
/**
 * The access token generated after adding our App to your shop.
 */
export type AdminAPIAccessToken = string;

export interface Configuration {
  shopName: ShopStoreName;
  access_token: AdminAPIAccessToken;
}
