/* tslint:disable */
// This file is generated
// Do not edit this file
import * as getProducts from "./getProducts/index";
export * as getProducts from "./getProducts/index";
import * as getProductVariants from "./getProductVariants/index";
export * as getProductVariants from "./getProductVariants/index";
import * as getCustomers from "./getCustomers/index";
export * as getCustomers from "./getCustomers/index";
import * as getCustomerOrders from "./getCustomerOrders/index";
export * as getCustomerOrders from "./getCustomerOrders/index";

export type Actions = {
  getProducts: getProducts.ActionGetProducts;
  getProductVariants: getProductVariants.ActionGetProductVariants;
  getCustomers: getCustomers.ActionGetCustomers;
  getCustomerOrders: getCustomerOrders.ActionGetCustomerOrders;
}
