/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Bloc {
  items: (
    | {
        type: "text";
        payload: {
          text: string;
        };
      }
    | {
        type: "markdown";
        payload: {
          markdown: string;
        };
      }
    | {
        type: "image";
        payload: {
          imageUrl: string;
        };
      }
    | {
        type: "audio";
        payload: {
          audioUrl: string;
        };
      }
    | {
        type: "video";
        payload: {
          videoUrl: string;
        };
      }
    | {
        type: "file";
        payload: {
          fileUrl: string;
          title?: string;
        };
      }
    | {
        type: "location";
        payload: {
          latitude: number;
          longitude: number;
          address?: string;
          title?: string;
        };
      }
  )[];
}
