/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * The product ID to retrieve its variants
 */
export type ProductIDS = string;
/**
 * Return up to this many results per page. Default is 50, Maximum is 250
 */
export type Limit = number;

export interface Input {
  product_id?: ProductIDS;
  limit?: Limit;
}
