/* tslint:disable */
// This file is generated
// Do not edit this file
import * as orderCreated from "./orderCreated";
export * as orderCreated from "./orderCreated";
import * as orderCancelled from "./orderCancelled";
export * as orderCancelled from "./orderCancelled";
import * as newCustomer from "./newCustomer";
export * as newCustomer from "./newCustomer";

export type Events = {
  orderCreated: orderCreated.OrderCreated;
  orderCancelled: orderCancelled.OrderCancelled;
  newCustomer: newCustomer.NewCustomer;
}
