/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface NewCustomer {
  type?: "shopify:newCustomer";
  shopName: string;
  id: number;
  email?: string | null;
  accepts_marketing?: boolean | null;
  first_name?: string | null;
  last_name?: string | null;
  orders_count?: number | null;
  state?: string | null;
  total_spent?: string | null;
  last_order_id?: string | null;
  note?: string | null;
}
