/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface OrderCancelled {
  type?: "shopify:orderCancelled";
  order_id: number;
  shopName: string;
  cancel_reason: string;
  closed_at?: string;
  currency?: string;
  current_subtotal_price?: string;
  current_total_discounts?: string;
  current_total_price?: string;
  current_total_tax?: string;
  customer_locale?: string;
  order_status_url?: string;
  fullBody: {
    [k: string]: any;
  };
}
