/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Comma-separated list of product IDs.
 */
export type ProductIDS = string;
/**
 * Return up to this many results per page. Default is 50, Maximum is 250
 */
export type Limit = number;
/**
 * The exact product title.
 */
export type ProductTitle = string;
/**
 * Exact product type.
 */
export type ProductType = string;

export interface Input {
  ids?: ProductIDS;
  limit?: Limit;
  title?: ProductTitle;
  product_type?: ProductType;
}
